openapi: 3.1.0
info:
  title: WebCheckout
  version: '1.0'
  description: |
    Webcheckout crea una página de pago segura alojada en Placetopay, ésta le permite cobrar los pagos rápidamente. Puede ser accedido desde diferentes dispositivos

    * **Diseño personalizado:** Puedes agregar tu imagen y colores corporativos.
    * **Diferentes idiomas y monedas:** Operaciones soportadas con diferentes idiomas y monedas
    * **Adaptado a diferentes resoluciones:** Diseño receptivo para diferentes dispositivos 
    * **Wallet Placetopay:** Placetopay cuenta con su propia billetera, bridando mayor seguridad y facilidad en el proceso de pago.
    * **Seguridad de la información:** Lineamientos PCI que garantizan seguridad en la captura y procesamiento de la información sensible dela tarjeta.
    * **Funciones adicionales:** Impuestos, pagos mixtos, suscripciones, cobros recurrentes, promociones y más. 

    **Importante:** El API de WebCheckOut está basado en REST. Para hacer uso de este servicio es necesario que tu sistema soporte comunicación con la versión 1.2 del protocolo TLS.
  license: {}
  contact:
    url: 'https://www.placetopay.com/web/contactanos/'
servers:
  - description: 'SandBox Colombia, Puerto Rico, Costa Rica, Panamá'
    url: 'https://test.placetopay.com/redirection'
  - url: 'https://test.placetopay.ec/redirection'
    description: SandBox Ecuador
paths:
  /api/session:
    post:
      summary: Crear sesión (CreateRequest)
      operationId: post-api-session
      description: Solicita la creación de la sesión  retorna el identificador y la URL de procesamiento.
      x-internal: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedirectRequest'
            examples:
              Crear Sesión simple:
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  payment:
                    reference: '1122334455'
                    description: Prueba
                    amount:
                      currency: USD
                      total: 100
                    allowPartial: false
                  expiration: '2021-12-30T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
              'Crear sesión de preautorización ':
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  type: checkin
                  payment:
                    reference: '1122334455'
                    description: Prueba
                    amount:
                      currency: USD
                      total: 100
                    allowPartial: false
                  expiration: '2021-12-30T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
              Crear sesión con pago mixto:
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  payment:
                    reference: '1122334455'
                    description: Prueba
                    amount:
                      currency: USD
                      total: 100
                    allowPartial: true
                  expiration: '2021-12-30T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
              Crear sesión con impuestos:
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  payment:
                    reference: '331122'
                    description: Reference
                    amount:
                      taxes:
                        - kind: stateTax
                          amount: 16.13
                        - kind: municipalTax
                          amount: 11.21
                        - kind: reducedStateTax
                          amount: 10.21
                      details:
                        - kind: tip
                          amount: 11
                        - kind: subtotal
                          amount: 11
                      currency: USD
                      total: 500
                    allowPartial: false
                  expiration: '2021-12-30T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
              Crear sesión con dispersión:
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  payment:
                    reference: '331122'
                    description: Reference
                    amount:
                      currency: USD
                      total: 500
                    allowPartial: false
                    dispersion:
                      - agreement: '1299'
                        agreementType: MERCHANT
                        amount:
                          currency: USD
                          total: 200
                      - agreement: ''
                        agreementType: MERCHANT
                        amount:
                          currency: USD
                          total: 300
                  expiration: '2021-12-30T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
              Crear sesión suscripción:
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  subscription:
                    reference: '331122'
                    description: Una suscripción de prueba
                  expiration: '2021-12-31T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
              Crear sesión con recurrencia:
                value:
                  locale: es_CO
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  payment:
                    reference: '331122'
                    description: Pago con recurrencia
                    amount:
                      currency: USD
                      total: 100
                    recurring:
                      periodicity: D
                      interval: '1'
                      nextPayment: '2021-12-30'
                      maxPeriods: '12'
                  expiration: '2022-12-15T00:00:00-05:00'
                  returnUrl: 'https://dnetix.co/p2p/client'
                  ipAddress: 127.0.0.1
                  userAgent: PlacetoPay Sandbox
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
                  requestId:
                    type: integer
                  processUrl:
                    type: string
              examples:
                Respuesta:
                  value:
                    status:
                      status: OK
                      reason: PC
                      message: La petición se ha procesado correctamente
                      date: '2021-11-30T15:08:27-05:00'
                    requestId: 1
                    processUrl: 'https://checkout-co.placetopay.com/session/1/cc9b8690b1f7228c78b759ce27d7e80a'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
              examples:
                Respuesta:
                  value:
                    status:
                      status: FAILED
                      reason: 401
                      message: Autenticación fallida 102
                      date: '2021-11-30T15:12:25-05:00'
    parameters: []
  '/api/session/{requestId}':
    parameters:
      - schema:
          type: string
        name: requestId
        in: path
        required: true
    post:
      summary: Consultar sesión (getRequestInformation)
      operationId: post-api-session-requestId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectInformation'
              examples:
                Aprobado:
                  value:
                    requestId: 1
                    status:
                      status: APPROVED
                      reason: '00'
                      message: La petición ha sido aprobada exitosamente
                      date: '2021-11-30T15:49:47-05:00'
                    request:
                      locale: es_CO
                      payer:
                        document: '1033332222'
                        documentType: CC
                        name: Name
                        surname: LastName
                        email: dnetix1@app.com
                        mobile: '3111111111'
                        address:
                          postalCode: '12345'
                      payment:
                        reference: '1122334455'
                        description: Prueba
                        amount:
                          currency: USD
                          total: 1000
                        allowPartial: false
                        subscribe: false
                      fields:
                        - keyword: _processUrl_
                          value: 'https://test.placetopay.com/redirection/session/1/cb0f71a1f1ecdfab3ac345d3d670b097'
                          displayOn: none
                      returnUrl: 'https://redirection.test/home'
                      ipAddress: 127.0.0.1
                      userAgent: PlacetoPay Sandbox
                      expiration: '2021-12-30T00:00:00-05:00'
                    payment:
                      - status:
                          status: APPROVED
                          reason: '00'
                          message: Aprobada
                          date: '2021-11-30T15:49:36-05:00'
                        internalReference: 1
                        paymentMethod: visa
                        paymentMethodName: Visa
                        issuerName: 'JPMORGAN CHASE BANK, N.A.'
                        amount:
                          from:
                            currency: USD
                            total: 1000
                          to:
                            currency: USD
                            total: 1000
                          factor: 1
                        authorization: '000000'
                        reference: '1122334455'
                        receipt: '241516'
                        franchise: DF_VS
                        refunded: false
                        processorFields:
                          - keyword: merchantCode
                            value: '7200076413'
                            displayOn: none
                          - keyword: terminalNumber
                            value: PT312002
                            displayOn: none
                          - keyword: credit
                            value:
                              code: '0'
                              type: '00'
                              groupCode: C
                              installments: 0
                            displayOn: none
                          - keyword: totalAmount
                            value: 1000
                            displayOn: none
                          - keyword: iceAmount
                            value: 0
                            displayOn: none
                          - keyword: bin
                            value: '411111'
                            displayOn: none
                          - keyword: expiration
                            value: '1229'
                            displayOn: none
                          - keyword: lastDigits
                            value: '1111'
                            displayOn: none
                    subscription: null
                Pendiente:
                  value:
                    requestId: 1
                    status:
                      status: PENDING
                      reason: PT
                      message: La petición se encuentra pendiente
                      date: '2021-11-30T15:45:57-05:00'
                    request:
                      locale: es_CO
                      payer:
                        document: '1033332222'
                        documentType: CC
                        name: Name
                        surname: lastName
                        email: dnetix1@app.com
                        mobile: '3111111111'
                        address:
                          postalCode: '12345'
                      payment:
                        reference: '1122334455'
                        description: Prueba
                        amount:
                          currency: USD
                          total: 1000
                        allowPartial: false
                        subscribe: false
                      fields:
                        - keyword: _processUrl_
                          value: 'https://test.placetopay.com/redirection/session/1/e0dfb6c7d6ab964b2377c825aef56a63'
                          displayOn: none
                      returnUrl: 'https://dnetix.co/p2p/client'
                      ipAddress: 127.0.0.1
                      userAgent: PlacetoPay Sandbox
                      expiration: '2021-12-30T00:00:00-05:00'
                    payment: null
                    subscription: null
                Rechazado:
                  value:
                    requestId: 1
                    status:
                      status: REJECTED
                      reason: XN
                      message: Se ha rechazado la petición
                      date: '2021-11-30T16:44:24-05:00'
                    request:
                      locale: es_CO
                      payer:
                        document: '1033332222'
                        documentType: CC
                        name: Name
                        surname: LastName
                        email: dnetix@app.com
                        mobile: '31111111111'
                        address:
                          postalCode: '12345'
                      payment:
                        reference: '331122'
                        description: Reference
                        amount:
                          currency: USD
                          total: 500
                        allowPartial: false
                        subscribe: false
                        dispersion:
                          - reference: '331122'
                            description: Reference
                            amount:
                              currency: USD
                              total: 200
                            allowPartial: false
                            subscribe: false
                            agreement: '26'
                            agreementType: AIRLINE
                          - reference: '331122'
                            description: Reference
                            amount:
                              currency: USD
                              total: 300
                            allowPartial: false
                            subscribe: false
                            agreementType: MERCHANT
                      fields:
                        - keyword: _processUrl_
                          value: 'https://test.placetopay.com/redirection/session/1/1dfbaf16c76c6ee83a63a956d704a9d1'
                          displayOn: none
                      returnUrl: 'https://redirection.test/home'
                      ipAddress: 127.0.0.1
                      userAgent: PlacetoPay Sandbox
                      expiration: '2021-12-30T00:00:00-05:00'
                    payment:
                      - status:
                          status: REJECTED
                          reason: '65'
                          message: '65'
                          date: '2021-11-30T16:22:19-05:00'
                        internalReference: 1
                        paymentMethod: visa
                        paymentMethodName: Visa
                        issuerName: 'CAIXA D''ESTALVIS UNIO DE CAIXES DE MANLLEU, SABADE'
                        amount:
                          from:
                            currency: USD
                            total: 500
                          to:
                            currency: USD
                            total: 500
                          factor: 1
                        authorization: '000000'
                        reference: '331122'
                        franchise: TS_VS
                        refunded: false
                        processorFields:
                          - keyword: totalAmount
                            value: 500
                            displayOn: none
                          - keyword: lastDigits
                            value: '6853'
                            displayOn: none
                        dispersion:
                          - status:
                              status: REJECTED
                              reason: '65'
                              message: '65'
                              date: '2021-11-30T16:34:17-05:00'
                            internalReference: 2
                            amount:
                              from:
                                currency: USD
                                total: 200
                              to:
                                currency: USD
                                total: 200
                              factor: 1
                            authorization: '000000'
                            franchise: TS_VS
                            refunded: false
                            agreement: 26
                            agreementType: AIRLINE
                          - status:
                              status: REJECTED
                              reason: '?C'
                              message: Pago abortado por el usuario
                              date: '2021-11-30T16:34:17-05:00'
                            internalReference: 3
                            amount:
                              from:
                                currency: USD
                                total: 300
                              to:
                                currency: USD
                                total: 300
                              factor: 1
                            authorization: '000000'
                            receipt: '000000'
                            franchise: ID_VS
                            refunded: false
                            agreementType: MERCHANT
                    subscription: null
      description: |
        Obtiene la información de la sesión, si en la sesión hay transacciones se muestra el detalle de las mismas.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Autentication'
            examples:
              Ejemplo:
                value:
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
          application/xml:
            schema:
              description: ''
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    login:
                      type: string
                      minLength: 1
                    tranKey:
                      type: string
                      minLength: 1
                    nonce:
                      type: string
                      minLength: 1
                    seed:
                      type: string
                      minLength: 1
                  required:
                    - login
                    - tranKey
                    - nonce
                    - seed
              required:
                - auth
  /api/reverse:
    post:
      summary: Reversar pago (ReversePayment)
      operationId: post-api-reverse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReverseResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  $ref: '#/components/schemas/Autentication'
                internalReference:
                  type: string
                  description: |
                    Referencia interna de la transacción a reversar que se encuentra en el listado de transacciones del getRequestInformation (payment).
      description: |
        Permite revertir un pago aprobado con el código de referencia interna.
  /api/collect:
    post:
      summary: Cobro usando token (Collect)
      operationId: post-api-collect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectRequest'
      description: |
        Permite realizar cobros sin la intervención del usuario usando medios de pago previamente suscritos.
      x-internal: false
  /api/transaction:
    post:
      summary: Acciones de transacción (TransactionPayment)
      operationId: post-api-transaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequest'
              examples:
                Checkout:
                  value:
                    status:
                      status: APPROVED
                      reason: '00'
                      message: Aprobada
                      date: '2021-11-30T09:36:00-05:00'
                    payment:
                      status:
                        status: APPROVED
                        reason: '00'
                        message: Aprobada
                        date: '2021-11-30T09:35:59-05:00'
                      internalReference: 643
                      paymentMethod: visa
                      paymentMethodName: Visa
                      issuerName: 'JPMORGAN CHASE BANK, N.A.'
                      amount:
                        from:
                          currency: USD
                          total: 500
                        to:
                          currency: USD
                          total: 500
                        factor: 1
                      authorization: '550044'
                      reference: '1122334455'
                      receipt: '499435368733'
                      franchise: PS_VS
                      refunded: false
                Reauthorization:
                  value:
                    status:
                      status: APPROVED
                      reason: '00'
                      message: Aprobada
                      date: '2021-11-30T09:26:50-05:00'
                    payment:
                      status:
                        status: APPROVED
                        reason: '00'
                        message: Aprobada
                        date: '2021-11-30T09:26:49-05:00'
                      internalReference: 642
                      paymentMethod: visa
                      paymentMethodName: Visa
                      issuerName: 'JPMORGAN CHASE BANK, N.A.'
                      amount:
                        from:
                          currency: USD
                          total: 500
                        to:
                          currency: USD
                          total: 500
                        factor: 1
                      authorization: '883327'
                      reference: '1122334455'
                      receipt: '657093859996'
                      franchise: PS_VS
                      refunded: false
                Reverse:
                  value:
                    status:
                      status: APPROVED
                      reason: '00'
                      message: Aprobada
                      date: '2021-11-30T09:37:46-05:00'
                    payment:
                      status:
                        status: APPROVED
                        reason: '00'
                        message: Aprobada
                        date: '2021-11-30T09:37:46-05:00'
                      internalReference: 644
                      paymentMethod: visa
                      paymentMethodName: Visa
                      issuerName: 'JPMORGAN CHASE BANK, N.A.'
                      amount:
                        from:
                          currency: USD
                          total: 500
                        to:
                          currency: USD
                          total: 1000
                        factor: 1
                      authorization: '550044'
                      reference: '1122334455'
                      receipt: '499435368733'
                      franchise: PS_VS
                      refunded: false
      description: 'Permite realizar operaciones básicas de preauthorización como CHECKOUT, REAUTHORIZATION (No aplica para Puerto Rico) y REVERSE, por otro lado también permite revertir un pago aprobado con el código de referencia interna.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionActionRequest'
            examples:
              Checkout:
                value:
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  internalReference: 640
                  amount:
                    currency: USD
                    total: '500'
                  action: checkout
              Reauthorization:
                value:
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  internalReference: 640
                  amount:
                    currency: USD
                    total: '500'
                  action: reauthorization
              Reverse:
                value:
                  auth:
                    login: c51ce410c124a10e0db5e4b97fc2af39
                    tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
                    nonce: NjE0OWVkODgwYjNhNw==
                    seed: '2021-09-21T09:34:48-05:00'
                  internalReference: 123
                  action: reverse
        description: ''
      x-internal: false
components:
  schemas:
    Person:
      description: Estructura que refleja la información de una persona involucrada en una transacción.
      type: object
      title: Person
      properties:
        document:
          type: string
          minLength: 1
        documentType:
          type: string
          minLength: 1
          description: NO USADO EN PUERTO RICO
        name:
          type: string
          minLength: 1
        surname:
          type: string
          minLength: 1
        company:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        mobile:
          type: string
          minLength: 1
        address:
          type: object
          properties:
            street:
              type: string
              minLength: 1
            city:
              type: string
              minLength: 1
            state:
              type: string
              minLength: 1
            postalCode:
              type: string
              minLength: 1
            country:
              type: string
              minLength: 1
    PaymentRequest:
      title: PaymentRequest
      type: object
      description: |
        Estructura que contiene la información acerca del pago de la transacción requerida al servicio web.
      properties:
        reference:
          type: string
          description: |
            Única referencia para la solicitud de pago.
        description:
          type: string
          description: |
            Descripción de la cuenta.
        amount:
          $ref: '#/components/schemas/Amount'
        allowPartial:
          type: boolean
          description: |
            Define si el monto a ser cobrado puede ser parcial.
        shipping:
          $ref: '#/components/schemas/Person'
        items:
          $ref: '#/components/schemas/Items'
        fields:
          $ref: '#/components/schemas/NameValuePair'
        recurring:
          $ref: '#/components/schemas/Recurring'
        subscribe:
          type: boolean
          description: |
            Permite solicitar un proceso de cobro y suscripción en la misma sesión.
        dispersion:
          $ref: '#/components/schemas/PaymentRequest'
      required:
        - reference
        - amount
    Payment:
      title: Payment
      type: object
      description: |
        Estructura que contiene la información acerca del Pago de la transacción requerida al servicio web.
      properties:
        reference:
          type: string
          description: |
            Única referencia para la solicitud de pago.
        description:
          type: string
          description: |
            Descripción de la cuenta.
        amount:
          $ref: '#/components/schemas/Amount'
        allowPartial:
          type: boolean
          description: |
            Define si el monto a ser cobrado puede ser parcial.
        shipping:
          $ref: '#/components/schemas/Person'
        items:
          $ref: '#/components/schemas/Items'
        fields:
          $ref: '#/components/schemas/NameValuePair'
        recurring:
          $ref: '#/components/schemas/Recurring'
        subscribe:
          type: boolean
          description: |
            Permite solicitar un proceso de cobro y suscripción en la misma sesión.
        dispersion:
          $ref: '#/components/schemas/PaymentRequest'
        agreement:
          type: integer
        agreementType:
          type: string
      required:
        - reference
        - amount
    Amount:
      title: Amount
      type: object
      properties:
        currency:
          type: string
        total:
          type: string
        taxes:
          $ref: '#/components/schemas/TaxDetail'
        details:
          $ref: '#/components/schemas/AmountDetail'
      required:
        - currency
        - total
    Items:
      title: Items
      type: object
      description: |
        Posee una colección de estructuras de elementos.
      properties:
        item:
          $ref: '#/components/schemas/Item'
    NameValuePair:
      description: |
        Se utiliza para definir un tipo de par clave-valor
      type: object
      properties:
        keyword:
          type: string
          minLength: 1
          description: |
            Clave para el par de valores del dato.
        value:
          type: string
          minLength: 1
          description: |
            Valor para el par de datos.
        displayOn:
          type: string
          minLength: 1
          description: |
            Bajo qué circunstancias el campo debe ser mostrado en la interfaz de redirección. [none, payment, receipt, both, approved]
    Recurring:
      description: Estructura que contiene la información requerida para una solicitud de pago recurrente.
      type: object
      properties:
        periodicity:
          type: string
          minLength: 1
          description: 'Periodicidad de la factura [D, M, Y]'
        interval:
          type: string
          minLength: 1
          description: |
            Intervalo asociado a la periodicidad.
        nextPayment:
          type: string
          minLength: 1
          description: Fecha del próximo pago.
          format: date
        maxPeriods:
          type:
            - string
            - integer
          minLength: 1
          description: |
            Número máximo de periodo (-1 en caso de que no haya restricción.)
        'dueDate ':
          type: string
          format: date
          description: |
            Fecha para finalizar el pago.
        'notificationUrl ':
          type: string
          description: |
            URL en el que el servicio notificará cada vez que se haga un pago recurrente.
      required:
        - periodicity
        - interval
        - nextPayment
        - maxPeriods
    Item:
      description: ''
      type: object
      properties:
        sku:
          type: string
          description: |
            Unidad en stock correspondiente (SKU) al artículo.
        name:
          type: string
          minLength: 1
          description: |
            Nombre del artículo.
        category:
          type: string
          minLength: 1
          description: |
            Puede ser [digital, physical].
        qty:
          type: string
          description: |
            Número de un artículo en particular.
        price:
          type: number
          description: |
            Costo del artículo.
        tax:
          type: number
          description: |
            Impuesto del artículo.
      required:
        - sku
    TaxDetail:
      title: TaxDetail
      type: object
      properties:
        kind:
          type: string
          description: 'Valor de clasificación, puede ser [valueAddedTax, exciseDuty].'
        amount:
          type: integer
          description: |
            Valor discriminado.
      required:
        - amount
      description: |
        Estructura para almacenar información sobre un impuesto.
    AmountDetail:
      title: AmountDetail
      type: object
      description: |
        Estructura para almacenar información sobre el valor.
      properties:
        kind:
          type: string
          description: "\tValor de clasificación, puede ser [discount, additional,\nvatDevolutionBase, shipping,\nhandlingFee, insurance,\ngiftWrap, subtotal, fee, tip]\n"
        amount:
          type: integer
          description: |
            Valor discriminado.
      required:
        - kind
        - amount
    SubscriptionRequest:
      title: SubscriptionRequest
      type: object
      description: |
        Estructura que contiene la información relacionada con una solicitud de suscripción para obtener un Token.
      properties:
        reference:
          type: string
        description:
          type: string
        fields:
          $ref: '#/components/schemas/NameValuePair'
      required:
        - reference
    RedirectRequest:
      title: RedirectRequest
      type: object
      description: |
        Estructura que contiene toda la información acerca de la transacción para ser procesada.
      x-examples:
        'Crear sesión básica ':
          locale: es_CO
          payer:
            name: Diego
            surname: osorio
            email: diego.calle4@placetopay.com
            documentType: CC
            document: '1036949824'
            mobile: '3102903560'
          payment:
            reference: '331122'
            description: Pago básico de ejemplo
            amount:
              currency: USD
              total: 100
            allowPartial: false
          expiration: '2021-06-31T00:00:00-05:00'
          returnUrl: 'https://mysite.com/response/3210'
          ipAddress: 127.0.0.1
          userAgent: PlacetoPay Sandbox
        Crear sesión checkin:
          locale: es_CO
          type: checkin
          payer:
            name: Diego
            surname: osorio
            email: diego.calle4@placetopay.com
            documentType: CC
            document: '1036949824'
            mobile: '3102903560'
          payment:
            reference: '331122'
            description: Pago básico de ejemplo
            amount:
              currency: USD
              total: 100
            allowPartial: false
          expiration: '2021-06-31T00:00:00-05:00'
          returnUrl: 'https://mysite.com/response/3210'
          ipAddress: 127.0.0.1
          userAgent: PlacetoPay Sandbox
      x-internal: false
      examples: []
      properties:
        locale:
          type: string
          description: |
            Definido con los códigos ISO 631-1 (language) y ISO 3166-1 alpha-2 (2-letras del país). ej. en_US, es_CO
        auth:
          $ref: '#/components/schemas/Autentication'
        payer:
          $ref: '#/components/schemas/Person'
        buyer:
          $ref: '#/components/schemas/Person'
        payment:
          $ref: '#/components/schemas/PaymentRequest'
        subscription:
          $ref: '#/components/schemas/SubscriptionRequest'
        fields:
          $ref: '#/components/schemas/NameValuePair'
        paymentMethod:
          type: string
          description: |
            Forzar el medio de pago en la interfaz de redirección, los códigos aceptados son los de la lista. Si necesita más de uno separarlos con coma. ej. visa,amex,master
        expiration:
          type: string
          format: date-time
          description: |
            Fecha de expiración de una solicitud, el usuario debe terminar el proceso antes de esta fecha. 
        returnUrl:
          type: string
          description: |
            URL de retorno es utilizada para redirigir al usuario una vez termina la operación de pago.
        cancelUrl:
          type: string
          description: |
            URL para retornar cuando el cliente aborte la operación.
        ipAddress:
          type: string
          description: |
            Dirección IP del usuario.
        userAgent:
          type: string
        skipResult:
          type: boolean
          description: |
            Si se envía el parámetro como true se omite la pantalla del resultado en redirección y una vez aprobado el pago regresa al comercio automaticamente.
        noBuyerFill:
          type: boolean
          description: |
            Por defecto se llenan los datos que se piden en redirección con los del comprador (buyer) enviados, si se envía como true se omite este autocompletado automático.
        type:
          type: string
          description: crear una sesión de tipo checkin
    Autentication:
      description: ''
      type: object
      title: Autentication
      examples:
        - auth:
            login: c51ce410c124a10e0db5e4b97fc2af39
            tranKey: VQOcRcVH2DfL6Y4B4SaK6yhoH/VOUveZ3xT16OQnvxE=
            nonce: NjE0OWVkODgwYjNhNw==
            seed: '2021-09-21T09:34:48-05:00'
      properties:
        login:
          type: string
          minLength: 1
          description: |
            Identificador del sitio.
        tranKey:
          type: string
          minLength: 1
          description: 'Llave transaccional, que está formada por la siguiente operación: Base64(SHA-1(nonce + seed + secretkey)). El nonce dentro de la operación es el original, es decir, el que no está en Base64.'
        nonce:
          type: string
          minLength: 1
          description: |
            Valor aleatorio para cada solicitud codificado en Base64.
        seed:
          type: string
          minLength: 1
          description: |
            Fecha actual, la cual se genera en formato ISO 8601.
    Status:
      description: |
        Estructura que contiene la información de la respuesta sobre una solicitud o pago, e informa el estado actual de la misma.
      type: object
      properties:
        status:
          type: string
          minLength: 1
          description: Estado de una petición o pago
        reason:
          type:
            - string
            - number
          description: |
            Código del motivo proporcionado.
        message:
          type: string
          minLength: 1
          description: |
            Descripción del código de razón.
        date:
          type: string
          minLength: 1
          format: date-time
          description: |
            Fecha y hora en que se genera el estado de pago.
      required:
        - status
        - reason
        - message
        - date
    Transaction:
      title: Transaction
      type: object
      description: |
        Estructura que contiene información sobre el proceso de pago de la transacción en PlacetoPay.
      properties:
        status:
          $ref: '#/components/schemas/Status'
        internalReference:
          type: integer
          description: |
            Referencia interna en PlacetoPay.
        reference:
          type: string
          description: |
            Referencia enviada por el comercio para la transacción.
        paymentMethod:
          type: string
          description: |
            Código del método de pago utilizado.
        paymentMethodName:
          type: string
          description: |
            Nombre del método de pago utilizado.
        issuerName:
          type: string
          description: |
            Nombre del emisor o del procesador.
        amount:
          $ref: '#/components/schemas/AmountConversion'
        receipt:
          type: string
          description: |
            Numero de recibo de la transacción.
        franchise:
          type: string
          description: |
            Franquicia de la tarjeta utilizada.
        refunded:
          type: boolean
        authorization:
          type: string
          description: |
            Código de autorización.
        processorFields:
          $ref: '#/components/schemas/NameValuePair'
        dispersion:
          $ref: '#/components/schemas/Transaction'
        agreement:
          type:
            - integer
            - 'null'
          description: Identificador de destinatario de la transacción. Para el sitio principal de la transacción.
        agreementType:
          type:
            - string
            - 'null'
          description: 'Valores: AIRLINE MERCHANT'
      required:
        - status
    AmountConversion:
      title: AmountConversion
      type: object
      description: |
        Estructura para definir el factor de conversión y los valores.
      properties:
        from:
          $ref: '#/components/schemas/AmountBase'
        to:
          $ref: '#/components/schemas/AmountBase'
        factor:
          type: string
    AmountBase:
      title: AmountBase
      type: object
      description: |
        Estructura que representa una cantidad que define la moneda y el total.
      properties:
        'currency ':
          type: string
          description: |
            Moneda acorde al ISO 4217 (alphabetic code).
        'total ':
          type: number
          description: |
            Valor total.
    SubscriptionResponse:
      title: SubscriptionResponse
      type: object
      description: |
        Estructura que contiene información para el método de pago suscripción.
      properties:
        status:
          $ref: '#/components/schemas/Status'
        type:
          type: string
          description: |
            Esta cadena dicta el tipo de suscripción que se devuelve, puede ser [token, cuenta]
        instrument:
          $ref: '#/components/schemas/NameValuePair'
      required:
        - status
    RedirectInformation:
      title: RedirectInformation
      type: object
      description: |
        Estructura de respuesta a una solicitud para una información de transacción.
      properties:
        status:
          $ref: '#/components/schemas/Status'
        request:
          $ref: '#/components/schemas/RedirectRequest'
        payment:
          $ref: '#/components/schemas/Transaction'
        subscription:
          $ref: '#/components/schemas/SubscriptionResponse'
    ReverseResponse:
      title: ReverseResponse
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
        payment:
          $ref: '#/components/schemas/PaymentRequest'
      description: |
        Estructura de respuesta a una solicitud de pago reversado.
    Instrument:
      title: Instrument
      type: object
      description: |
        Estructura que contiene los detalles de un medio de pago suscrito.
      properties:
        token:
          $ref: '#/components/schemas/SimpleToken'
    SimpleToken:
      title: SimpleToken
      type: object
      description: |
        Estructura que contiene los detalles de un token previamente obtenido mediante un proceso de suscripción, se debe enviar el token o el subtoken en los casos que se habilite, no es necesario enviar ambos.
      properties:
        token:
          type: string
          description: |
            Token completo para tarjeta de crédito, debe ser usada para solicitar cualquier transacción a PlacetoPay.
        subtoken:
          type: string
          description: |
            Representación numérica del Token para casos donde es requerido un número adicional que parece como una tarjeta de crédito, los últimos 4 dígitos son iguales a los últimos 4 dígitos de la tarjeta de crédito.
        installments:
          type: integer
          description: |
            Número de cuotas en las cuales se solicita el cobro (opcional).
        cvv:
          type: string
          description: |
            Dígitos del código de seguridad de la tarjeta a usar en los casos en los que sea necesario, generalmente se deja en blanco si se tiene una terminal sin validación de CVV.
    CollectRequest:
      title: CollectRequest
      type: object
      description: |
        Permite realizar cobros sin la intervención del usuario usando medios de pago previamente suscritos.
      properties:
        payer:
          $ref: '#/components/schemas/Person'
        payment:
          $ref: '#/components/schemas/PaymentRequest'
        instrument:
          $ref: '#/components/schemas/Instrument'
      required:
        - payer
        - payment
        - instrument
    TransactionActionRequest:
      title: TransactionActionRequest
      type: object
      description: 'Estructura que permite realizar solicitudes de preauthorización como CHECKOUT, REAUTHORIZATION y REVERSE'
      x-examples:
        checkout example:
          internalReference: 1
          amount:
            currency: USD
            total: 100
          action: checkout
        reauthorization example:
          internalReference: 1
          amount:
            currency: USD
            total: 100
          action: reauthorization
        reverse example:
          internalReference: 1
          action: reverse
      properties:
        auth:
          $ref: '#/components/schemas/Autentication'
        internalReference:
          type: integer
        amount:
          $ref: '#/components/schemas/Amount'
        action:
          type: string
          example: checkout
      required:
        - internalReference
        - action
      examples: []
    DirectResponse:
      title: DirectResponse
      type: object
      description: Estructura que contiene los detalles de del transacción
      properties:
        requestId:
          type: number
        status:
          $ref: '#/components/schemas/Status'
        transaction:
          $ref: '#/components/schemas/Transaction'
        processUrl:
          type:
            - string
            - 'null'
        file:
          type:
            - string
            - 'null'
        policies:
          type: array
          items: {}
  securitySchemes: {}
